<a href="https://colab.research.google.com/github/malikjunaidgul/DataAnalytics/blob/main/Lecture_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Staring with Reading the data from csv file. Some of the ways in python. Let get started.

With Pandas

In [1]:
import pandas as pd
df = pd.read_csv('ds_salaries.csv')

In [5]:
import csv

with open('ds_salaries.csv', mode='r') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        print(row)

['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']
['2023', 'SE', 'FT', 'Principal Data Scientist', '80000', 'EUR', '85847', 'ES', '100', 'ES', 'L']
['2023', 'MI', 'CT', 'ML Engineer', '30000', 'USD', '30000', 'US', '100', 'US', 'S']
['2023', 'MI', 'CT', 'ML Engineer', '25500', 'USD', '25500', 'US', '100', 'US', 'S']
['2023', 'SE', 'FT', 'Data Scientist', '175000', 'USD', '175000', 'CA', '100', 'CA', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '120000', 'USD', '120000', 'CA', '100', 'CA', 'M']
['2023', 'SE', 'FT', 'Applied Scientist', '222200', 'USD', '222200', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Applied Scientist', '136000', 'USD', '136000', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Data Scientist', '219000', 'USD', '219000', 'CA', '0', 'CA', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '141000', 'USD', '141000', 'CA', '0', 'CA', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '147100', 'USD', '147100', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '90700', 'USD', '90700', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '130000', 'USD', '130000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '100000', 'USD', '100000', 'US', '100', 'US', 'M']
['2023', 'EN', 'FT', 'Applied Scientist', '213660', 'USD', '213660', 'US', '0', 'US', 'L']
['2023', 'EN', 'FT', 'Applied Scientist', '130760', 'USD', '130760', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Data Modeler', '147100', 'USD', '147100', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Modeler', '90700', 'USD', '90700', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '170000', 'USD', '170000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '150000', 'USD', '150000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Analyst', '150000', 'USD', '150000', 'US', '100', 'US', 'M']
['2023', 'MI', 'FT', 'Data Analyst', '110000', 'USD', '110000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Research Engineer', '275000', 'USD', '275000', 'DE', '0', 'DE', 'M']
['2023', 'SE', 'FT', 'Research Engineer', '174000', 'USD', '174000', 'DE', '0', 'DE', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '230000', 'USD', '230000', 'GB', '100', 'GB', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '143200', 'USD', '143200', 'GB', '100', 'GB', 'M']
['2023', 'SE', 'FT', 'Business Intelligence Engineer', '225000', 'USD', '225000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Business Intelligence Engineer', '156400', 'USD', '156400', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '200000', 'USD', '200000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Strategist', '90000', 'USD', '90000', 'CA', '0', 'CA', 'M']
['2023', 'SE', 'FT', 'Data Strategist', '72000', 'USD', '72000', 'CA', '0', 'CA', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '253200', 'USD', '253200', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '90700', 'USD', '90700', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Computer Vision Engineer', '342810', 'USD', '342810', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Computer Vision Engineer', '184590', 'USD', '184590', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Engineer', '162500', 'USD', '162500', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Analyst', '105380', 'USD', '105380', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Analyst', '64500', 'USD', '64500', 'US', '0', 'US', 'M']
['2023', 'EN', 'FT', 'Data Quality Analyst', '100000', 'USD', '100000', 'NG', '100', 'NG', 'L']
['2023', 'EN', 'FT', 'Compliance Data Analyst', '30000', 'USD', '30000', 'NG', '100', 'NG', 'L']
['2022', 'MI', 'FT', 'Machine Learning Engineer', '1650000', 'INR', '20984', 'IN', '50', 'IN', 'L']
['2023', 'EN', 'FT', 'Applied Scientist', '204620', 'USD', '204620', 'US', '0', 'US', 'L']
['2023', 'EN', 'FT', 'Applied Scientist', '110680', 'USD', '110680', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Data Engineer', '270703', 'USD', '270703', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '221484', 'USD', '221484', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '212750', 'USD', '212750', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '185000', 'USD', '185000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '262000', 'USD', '262000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '245000', 'USD', '245000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '275300', 'USD', '275300', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '183500', 'USD', '183500', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '218500', 'USD', '218500', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '199098', 'USD', '199098', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '203300', 'USD', '203300', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '123600', 'USD', '123600', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Research Engineer', '189110', 'USD', '189110', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Research Engineer', '139000', 'USD', '139000', 'US', '0', 'US', 'M']
['2023', 'EX', 'FT', 'Data Scientist', '258750', 'USD', '258750', 'US', '0', 'US', 'M']
['2023', 'EX', 'FT', 'Data Scientist', '185000', 'USD', '185000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '231500', 'USD', '231500', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '166000', 'USD', '166000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '172500', 'USD', '172500', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '110500', 'USD', '110500', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '238000', 'USD', '238000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '176000', 'USD', '176000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '237000', 'USD', '237000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '201450', 'USD', '201450', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Applied Scientist', '309400', 'USD', '309400', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Applied Scientist', '159100', 'USD', '159100', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Data Engineer', '115000', 'USD', '115000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '81500', 'USD', '81500', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '237000', 'USD', '237000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '201450', 'USD', '201450', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Computer Vision Engineer', '280000', 'USD', '280000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Computer Vision Engineer', '210000', 'USD', '210000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Architect', '280100', 'USD', '280100', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Architect', '168100', 'USD', '168100', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '193500', 'USD', '193500', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '139000', 'USD', '139000', 'US', '100', 'US', 'M']
['2023', 'MI', 'FT', 'Data Scientist', '510000', 'HKD', '65062', 'HK', '0', 'HK', 'L']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '150000', 'USD', '150000', 'PT', '100', 'US', 'M']
['2023', 'MI', 'FT', 'Applied Machine Learning Engineer', '65000', 'EUR', '69751', 'IN', '100', 'DE', 'S']
['2022', 'EN', 'FT', 'AI Developer', '300000', 'USD', '300000', 'IN', '50', 'IN', 'L']
['2023', 'MI', 'FT', 'Machine Learning Engineer', '90000', 'EUR', '96578', 'NL', '100', 'NL', 'L']
['2023', 'SE', 'FT', 'Business Intelligence Engineer', '185900', 'USD', '185900', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Business Intelligence Engineer', '129300', 'USD', '129300', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '225000', 'USD', '225000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '175000', 'USD', '175000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '185000', 'USD', '185000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '140000', 'USD', '140000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '45000', 'EUR', '48289', 'ES', '0', 'ES', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '36000', 'EUR', '38631', 'ES', '0', 'ES', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '105000', 'USD', '105000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '70000', 'USD', '70000', 'US', '0', 'US', 'M']
['2023', 'EN', 'FT', 'Machine Learning Engineer', '163196', 'USD', '163196', 'US', '0', 'US', 'M']
['2023', 'EN', 'FT', 'Machine Learning Engineer', '145885', 'USD', '145885', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '217000', 'USD', '217000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '185000', 'USD', '185000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '202800', 'USD', '202800', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Data Analyst', '104300', 'USD', '104300', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Data Analyst', '145000', 'USD', '145000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '65000', 'USD', '65000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '165000', 'USD', '165000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '132300', 'USD', '132300', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '179170', 'USD', '179170', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '94300', 'USD', '94300', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '152500', 'USD', '152500', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '116450', 'USD', '116450', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '247300', 'USD', '247300', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '133800', 'USD', '133800', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Research Engineer', '203000', 'USD', '203000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Research Engineer', '133000', 'USD', '133000', 'US', '0', 'US', 'M']
['2023', 'EN', 'FT', 'Research Scientist', '220000', 'USD', '220000', 'US', '50', 'US', 'L']
['2022', 'EN', 'FT', 'Machine Learning Engineer', '54000', 'CHF', '56536', 'CH', '100', 'CH', 'S']
['2023', 'SE', 'FT', 'Data Scientist', '150000', 'USD', '150000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '120000', 'USD', '120000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '289800', 'USD', '289800', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '214000', 'USD', '214000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '179820', 'USD', '179820', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '143860', 'USD', '143860', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '283200', 'USD', '283200', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '188800', 'USD', '188800', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '289800', 'USD', '289800', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '214200', 'USD', '214200', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '185900', 'USD', '185900', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '129300', 'USD', '129300', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '252000', 'USD', '252000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '129000', 'USD', '129000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Analytics Manager', '155000', 'USD', '155000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Analytics Manager', '140000', 'USD', '140000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '161800', 'USD', '161800', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '141600', 'USD', '141600', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '342300', 'USD', '342300', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '176100', 'USD', '176100', 'US', '0', 'US', 'L']
['2023', 'MI', 'FT', 'Data Engineer', '100000', 'USD', '100000', 'US', '100', 'US', 'M']
['2023', 'MI', 'FT', 'Data Engineer', '70000', 'USD', '70000', 'US', '100', 'US', 'M']
['2023', 'EN', 'FT', 'Data Engineer', '85000', 'USD', '85000', 'US', '0', 'US', 'M']
['2023', 'EN', 'FT', 'Data Engineer', '65000', 'USD', '65000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '138784', 'USD', '138784', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '83270', 'USD', '83270', 'US', '100', 'US', 'M']
['2023', 'EN', 'FT', 'Data Analyst', '75000', 'USD', '75000', 'US', '0', 'US', 'M']
['2023', 'EN', 'FT', 'Data Analyst', '70000', 'USD', '70000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '204500', 'USD', '204500', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '138900', 'USD', '138900', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '318300', 'USD', '318300', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '212200', 'USD', '212200', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '95000', 'USD', '95000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '75000', 'USD', '75000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '195000', 'USD', '195000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '160000', 'USD', '160000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '230000', 'USD', '230000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '143200', 'USD', '143200', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Engineer', '100000', 'USD', '100000', 'US', '100', 'US', 'M']
['2023', 'MI', 'FT', 'Data Engineer', '70000', 'USD', '70000', 'US', '100', 'US', 'M']
['2023', 'MI', 'FT', 'Business Data Analyst', '105000', 'USD', '105000', 'US', '50', 'US', 'L']
['2023', 'MI', 'FT', 'Applied Data Scientist', '1700000', 'INR', '20670', 'IN', '100', 'IN', 'L']
['2023', 'MI', 'FT', 'Data Analyst', '38000', 'GBP', '46178', 'GB', '0', 'GB', 'M']
['2023', 'MI', 'FT', 'Data Analyst', '35000', 'GBP', '42533', 'GB', '0', 'GB', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '145000', 'USD', '145000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '115000', 'USD', '115000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '168400', 'USD', '168400', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '105200', 'USD', '105200', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Applied Scientist', '309400', 'USD', '309400', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Applied Scientist', '159100', 'USD', '159100', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '190000', 'USD', '190000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '150000', 'USD', '150000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Engineer', '162500', 'USD', '162500', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '150000', 'USD', '150000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Analytics Engineer', '120000', 'USD', '120000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '145000', 'USD', '145000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '120000', 'USD', '120000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Applied Scientist', '222200', 'USD', '222200', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Applied Scientist', '136000', 'USD', '136000', 'US', '0', 'US', 'L']
['2023', 'SE', 'FT', 'Data Analyst', '45000', 'GBP', '54685', 'CF', '100', 'CF', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '35000', 'GBP', '42533', 'CF', '100', 'CF', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '241000', 'USD', '241000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '155000', 'USD', '155000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '220000', 'USD', '220000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '190000', 'USD', '190000', 'US', '100', 'US', 'M']
['2023', 'MI', 'FT', 'Data Scientist', '55000', 'GBP', '66837', 'GB', '0', 'GB', 'M']
['2023', 'MI', 'FT', 'Data Scientist', '45000', 'GBP', '54685', 'GB', '0', 'GB', 'M']
['2020', 'EX', 'FT', 'Staff Data Analyst', '15000', 'USD', '15000', 'NG', '0', 'CA', 'M']
['2023', 'MI', 'FT', 'ETL Engineer', '70000', 'GBP', '85066', 'GB', '100', 'GB', 'M']
['2023', 'MI', 'FT', 'ETL Engineer', '47500', 'GBP', '57723', 'GB', '100', 'GB', 'M']
['2023', 'EN', 'FT', 'Data Analyst', '85000', 'USD', '85000', 'US', '100', 'US', 'M']
['2023', 'EN', 'FT', 'Data Analyst', '75000', 'USD', '75000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '160000', 'USD', '160000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '140000', 'USD', '140000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Machine Learning Engineer', '300000', 'USD', '300000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Machine Learning Engineer', '250000', 'USD', '250000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '228000', 'USD', '228000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '186000', 'USD', '186000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '190000', 'USD', '190000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '170000', 'USD', '170000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Research Engineer', '230000', 'USD', '230000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Research Engineer', '200000', 'USD', '200000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Architect', '180000', 'USD', '180000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Architect', '115000', 'USD', '115000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Architect', '200000', 'USD', '200000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Architect', '115000', 'USD', '115000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data DevOps Engineer', '50000', 'EUR', '53654', 'FR', '50', 'FR', 'S']
['2023', 'EX', 'FT', 'Data Engineer', '220000', 'USD', '220000', 'US', '0', 'US', 'M']
['2023', 'EX', 'FT', 'Data Engineer', '205000', 'USD', '205000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Engineer', '180000', 'USD', '180000', 'US', '0', 'US', 'M']
['2023', 'MI', 'FT', 'Data Engineer', '130000', 'USD', '130000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '200000', 'USD', '200000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Engineer', '150000', 'USD', '150000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Computer Vision Engineer', '215000', 'USD', '215000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Computer Vision Engineer', '170000', 'USD', '170000', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '247500', 'USD', '247500', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Machine Learning Engineer', '172200', 'USD', '172200', 'US', '0', 'US', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '224000', 'USD', '224000', 'CA', '0', 'CA', 'M']
['2023', 'SE', 'FT', 'Data Scientist', '176000', 'USD', '176000', 'CA', '0', 'CA', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '120000', 'USD', '120000', 'US', '100', 'US', 'M']
['2023', 'SE', 'FT', 'Data Analyst', '75000', 'USD', '75000', 'US', '100', 'US', 'M']
['2023', 'EN', 'FT', 'Data Engineer', '1400000', 'INR', '17022', 'IN', '100', 'IN', 'L']
['2023', 'SE', 'FT', 'Applied Data Scientist', '100000', 'AUD', '68318', 'AU', '100', 'FI', 'M']

In [7]:
import numpy as np
data = np.genfromtxt('ds_salaries.csv', delimiter=',', skip_header=1)

In [8]:
data

array([[2023.,   nan,   nan, ...,  100.,   nan,   nan],
       [2023.,   nan,   nan, ...,  100.,   nan,   nan],
       [2023.,   nan,   nan, ...,  100.,   nan,   nan],
       ...,
       [2020.,   nan,   nan, ...,  100.,   nan,   nan],
       [2020.,   nan,   nan, ...,  100.,   nan,   nan],
       [2021.,   nan,   nan, ...,   50.,   nan,   nan]])

In [9]:
import csv

with open('ds_salaries.csv', mode='r') as file:
    csv_reader = csv.DictReader(file)
    for row in csv_reader:
        print(row)

{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Principal Data Scientist', 'salary': '80000', 'salary_currency': 'EUR', 'salary_in_usd': '85847', 'employee_residence': 'ES', 'remote_ratio': '100', 'company_location': 'ES', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'MI', 'employment_type': 'CT', 'job_title': 'ML Engineer', 'salary': '30000', 'salary_currency': 'USD', 'salary_in_usd': '30000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'S'}
{'work_year': '2023', 'experience_level': 'MI', 'employment_type': 'CT', 'job_title': 'ML Engineer', 'salary': '25500', 'salary_currency': 'USD', 'salary_in_usd': '25500', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'S'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '175000', 'salary_currency': 'USD', 'salary_in_usd': '175000', 'employee_residence': 'CA', 'remote_ratio': '100', 'company_location': 'CA', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '120000', 'salary_currency': 'USD', 'salary_in_usd': '120000', 'employee_residence': 'CA', 'remote_ratio': '100', 'company_location': 'CA', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Applied Scientist', 'salary': '222200', 'salary_currency': 'USD', 'salary_in_usd': '222200', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Applied Scientist', 'salary': '136000', 'salary_currency': 'USD', 'salary_in_usd': '136000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '219000', 'salary_currency': 'USD', 'salary_in_usd': '219000', 'employee_residence': 'CA', 'remote_ratio': '0', 'company_location': 'CA', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '141000', 'salary_currency': 'USD', 'salary_in_usd': '141000', 'employee_residence': 'CA', 'remote_ratio': '0', 'company_location': 'CA', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '147100', 'salary_currency': 'USD', 'salary_in_usd': '147100', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '90700', 'salary_currency': 'USD', 'salary_in_usd': '90700', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Analyst', 'salary': '130000', 'salary_currency': 'USD', 'salary_in_usd': '130000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Analyst', 'salary': '100000', 'salary_currency': 'USD', 'salary_in_usd': '100000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'EN', 'employment_type': 'FT', 'job_title': 'Applied Scientist', 'salary': '213660', 'salary_currency': 'USD', 'salary_in_usd': '213660', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'EN', 'employment_type': 'FT', 'job_title': 'Applied Scientist', 'salary': '130760', 'salary_currency': 'USD', 'salary_in_usd': '130760', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Modeler', 'salary': '147100', 'salary_currency': 'USD', 'salary_in_usd': '147100', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Modeler', 'salary': '90700', 'salary_currency': 'USD', 'salary_in_usd': '90700', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '170000', 'salary_currency': 'USD', 'salary_in_usd': '170000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '150000', 'salary_currency': 'USD', 'salary_in_usd': '150000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'MI', 'employment_type': 'FT', 'job_title': 'Data Analyst', 'salary': '150000', 'salary_currency': 'USD', 'salary_in_usd': '150000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'MI', 'employment_type': 'FT', 'job_title': 'Data Analyst', 'salary': '110000', 'salary_currency': 'USD', 'salary_in_usd': '110000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Research Engineer', 'salary': '275000', 'salary_currency': 'USD', 'salary_in_usd': '275000', 'employee_residence': 'DE', 'remote_ratio': '0', 'company_location': 'DE', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Research Engineer', 'salary': '174000', 'salary_currency': 'USD', 'salary_in_usd': '174000', 'employee_residence': 'DE', 'remote_ratio': '0', 'company_location': 'DE', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Analytics Engineer', 'salary': '230000', 'salary_currency': 'USD', 'salary_in_usd': '230000', 'employee_residence': 'GB', 'remote_ratio': '100', 'company_location': 'GB', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Analytics Engineer', 'salary': '143200', 'salary_currency': 'USD', 'salary_in_usd': '143200', 'employee_residence': 'GB', 'remote_ratio': '100', 'company_location': 'GB', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Business Intelligence Engineer', 'salary': '225000', 'salary_currency': 'USD', 'salary_in_usd': '225000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Business Intelligence Engineer', 'salary': '156400', 'salary_currency': 'USD', 'salary_in_usd': '156400', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Machine Learning Engineer', 'salary': '200000', 'salary_currency': 'USD', 'salary_in_usd': '200000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Machine Learning Engineer', 'salary': '130000', 'salary_currency': 'USD', 'salary_in_usd': '130000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Strategist', 'salary': '90000', 'salary_currency': 'USD', 'salary_in_usd': '90000', 'employee_residence': 'CA', 'remote_ratio': '0', 'company_location': 'CA', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Strategist', 'salary': '72000', 'salary_currency': 'USD', 'salary_in_usd': '72000', 'employee_residence': 'CA', 'remote_ratio': '0', 'company_location': 'CA', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '253200', 'salary_currency': 'USD', 'salary_in_usd': '253200', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '90700', 'salary_currency': 'USD', 'salary_in_usd': '90700', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Computer Vision Engineer', 'salary': '342810', 'salary_currency': 'USD', 'salary_in_usd': '342810', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Computer Vision Engineer', 'salary': '184590', 'salary_currency': 'USD', 'salary_in_usd': '184590', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'MI', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '162500', 'salary_currency': 'USD', 'salary_in_usd': '162500', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'MI', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '130000', 'salary_currency': 'USD', 'salary_in_usd': '130000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'MI', 'employment_type': 'FT', 'job_title': 'Data Analyst', 'salary': '105380', 'salary_currency': 'USD', 'salary_in_usd': '105380', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'MI', 'employment_type': 'FT', 'job_title': 'Data Analyst', 'salary': '64500', 'salary_currency': 'USD', 'salary_in_usd': '64500', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'EN', 'employment_type': 'FT', 'job_title': 'Data Quality Analyst', 'salary': '100000', 'salary_currency': 'USD', 'salary_in_usd': '100000', 'employee_residence': 'NG', 'remote_ratio': '100', 'company_location': 'NG', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'EN', 'employment_type': 'FT', 'job_title': 'Compliance Data Analyst', 'salary': '30000', 'salary_currency': 'USD', 'salary_in_usd': '30000', 'employee_residence': 'NG', 'remote_ratio': '100', 'company_location': 'NG', 'company_size': 'L'}
{'work_year': '2022', 'experience_level': 'MI', 'employment_type': 'FT', 'job_title': 'Machine Learning Engineer', 'salary': '1650000', 'salary_currency': 'INR', 'salary_in_usd': '20984', 'employee_residence': 'IN', 'remote_ratio': '50', 'company_location': 'IN', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'EN', 'employment_type': 'FT', 'job_title': 'Applied Scientist', 'salary': '204620', 'salary_currency': 'USD', 'salary_in_usd': '204620', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'EN', 'employment_type': 'FT', 'job_title': 'Applied Scientist', 'salary': '110680', 'salary_currency': 'USD', 'salary_in_usd': '110680', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '270703', 'salary_currency': 'USD', 'salary_in_usd': '270703', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '221484', 'salary_currency': 'USD', 'salary_in_usd': '221484', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '212750', 'salary_currency': 'USD', 'salary_in_usd': '212750', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '185000', 'salary_currency': 'USD', 'salary_in_usd': '185000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '262000', 'salary_currency': 'USD', 'salary_in_usd': '262000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '245000', 'salary_currency': 'USD', 'salary_in_usd': '245000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '275300', 'salary_currency': 'USD', 'salary_in_usd': '275300', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '183500', 'salary_currency': 'USD', 'salary_in_usd': '183500', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '218500', 'salary_currency': 'USD', 'salary_in_usd': '218500', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '199098', 'salary_currency': 'USD', 'salary_in_usd': '199098', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '203300', 'salary_currency': 'USD', 'salary_in_usd': '203300', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '123600', 'salary_currency': 'USD', 'salary_in_usd': '123600', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Research Engineer', 'salary': '189110', 'salary_currency': 'USD', 'salary_in_usd': '189110', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Research Engineer', 'salary': '139000', 'salary_currency': 'USD', 'salary_in_usd': '139000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'EX', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '258750', 'salary_currency': 'USD', 'salary_in_usd': '258750', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'EX', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '185000', 'salary_currency': 'USD', 'salary_in_usd': '185000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '231500', 'salary_currency': 'USD', 'salary_in_usd': '231500', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '166000', 'salary_currency': 'USD', 'salary_in_usd': '166000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '172500', 'salary_currency': 'USD', 'salary_in_usd': '172500', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Scientist', 'salary': '110500', 'salary_currency': 'USD', 'salary_in_usd': '110500', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '238000', 'salary_currency': 'USD', 'salary_in_usd': '238000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '176000', 'salary_currency': 'USD', 'salary_in_usd': '176000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '237000', 'salary_currency': 'USD', 'salary_in_usd': '237000', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '201450', 'salary_currency': 'USD', 'salary_in_usd': '201450', 'employee_residence': 'US', 'remote_ratio': '100', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Applied Scientist', 'salary': '309400', 'salary_currency': 'USD', 'salary_in_usd': '309400', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Applied Scientist', 'salary': '159100', 'salary_currency': 'USD', 'salary_in_usd': '159100', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'L'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '115000', 'salary_currency': 'USD', 'salary_in_usd': '115000', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}
{'work_year': '2023', 'experience_level': 'SE', 'employment_type': 'FT', 'job_title': 'Data Engineer', 'salary': '81500', 'salary_currency': 'USD', 'salary_in_usd': '81500', 'employee_residence': 'US', 'remote_ratio': '0', 'company_location': 'US', 'company_size': 'M'}

In [10]:
import dask.dataframe as dd
df = dd.read_csv('ds_salaries.csv')

/usr/local/lib/python3.11/dist-packages/dask/dataframe/__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

In [11]:
df

Dask DataFrame Structure:
              work_year experience_level employment_type job_title salary salary_currency salary_in_usd employee_residence remote_ratio company_location company_size
npartitions=1
                  int64           string          string    string  int64          string         int64             string        int64           string       string
                    ...              ...             ...       ...    ...             ...           ...                ...          ...              ...          ...
Dask Name: to_pyarrow_string, 2 graph layers